### ISSUE TITLE
Pre Release Link

### ISSUE THREAD

**Issue by X-Raym** [Jeff0S/sws-web#1]
Hi,

Last pre-release is almost one year old,
and is actually used by a lot of users, and is even required by some scripts. It seems to work nicely for both mac and windows.
- I think it would be nice to have download links to pre-releases builds right for the website so the users can have direct access to them, with a nice front-end display rather than a simple html blank page.
- Also, maybe the current v2.8.7.0 can be consider as stable now.

Thanks for your consideration ! 👍

**Comment by X-Raym** [comment]
@swstim Any thought about that ? :)

**Comment by swstim** [comment]
Now that I've got a release out I think I will keep the pre-release section as is for now.
